name: Prod Cloud Functions

on:
  push:
    branches:
      - master
    paths:
      - "functions/**"
      - "!functions/patches/**"

defaults:
  run:
    working-directory: functions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm ci
      - name: set credential file
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > credential.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      # - run: npm test
      #   env:
      #     FIREBASE_CONFIG_TEST: ${{ secrets.FIREBASE_CONFIG_TEST }}
      #     TEST_MEMBER_ID: ${{ secrets.TEST_MEMBER_ID }}
      - name: install firebase-tools
        run: npm install -g firebase-tools
      - name: Deploy functions
        # masterブランチにないfunctionsがデプロイされていると「削除しますか」の確認されるが、CI環境だとNoと答えられないので、エラーがでる。
        # しかし、echo "y\n"を仕込んでおくことでYesと答えることができる
        # ref) https://github.com/firebase/firebase-tools/issues/877#issuecomment-550976371
        run: echo "y\n" | firebase deploy --only functions --interactive --token=${{ secrets.FIREBASE_TOKEN }} --project=default
        env:
          RESOURCE_DIR: functions
