name: Prod Hosting

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'functions/**'
    - '.github/**'
    - 'README.md'
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run lint:ci
    - run: npm run test:unit
    - run: npm run build:prod
      env:
        VUE_APP_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        VUE_APP_PAYMENT_JS_URL: ${{ secrets.VUE_APP_PAYMENT_JS_URL }}
        VUE_APP_PAYMENT_JS_APIKEY: ${{ secrets.VUE_APP_PAYMENT_JS_APIKEY }}
        VUE_APP_PAYMENT_PAGE_BASE_URL: ${{ secrets.VUE_APP_PAYMENT_PAGE_BASE_URL }}
        VUE_APP_ROLLBAR_ACCESS_TOKEN: ${{ secrets.VUE_APP_ROLLBAR_ACCESS_TOKEN }}
        VUE_APP_ROLLBAR_ENV: mikiwame-prod
    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v1.3.0
      with:
        args: deploy --only hosting --project=default
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
